In [4]:
import pandas as pd

In [7]:
df_olympics = pd.read_csv('data/bios_raw.csv')
df_olympics.sample(3)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
69907,Competed in Olympic Games,Male,Franz Paul•Nettelbeck,Paul•Nettelbeck,"23 April 1889 in Berlin, Berlin (GER)","14 June 1963 in Salzburg, Salzburg (AUT)",Germany,70428,NaN,"Charlottenburger Sport-Club, Berlin (GER)",NaN,NaN,NaN,NaN,NaN,NaN
24950,Competed in Olympic Games,Male,Albert Alexandre•Parsis,Albert•Parsis,"2 June 1890 in Tourcoing, Nord (FRA)","24 February 1980 in Tourcoing, Nord (FRA)",France,25139,NaN,"US Tourcoing, Tourcoing (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
49318,Competed in Olympic Games,Female,Karin Doris•Brandes Pérez,Karin•Brandes,"26 September 1967 in Lima, Lima (PER)",NaN,Peru,49675,169 cm / 58 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# make a copy of df
df = df_olympics.copy()

In [9]:
# cleanup full name remove the '•' string
df["name"] = df['Full name'].str.replace('•',' ')
# df[["name", "Full name"]].sample(5)

In [10]:
df.sample(4)

# df.info()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
49718,Competed in Olympic Games,Female,"Yu Fen ""May""•Ooi",May•Ooi,24 June 1976,NaN,Singapore,50076,NaN,People's Association Youth Swimming Club,NaN,NaN,NaN,NaN,NaN,NaN,"Yu Fen ""May"" Ooi"
85032,Competed in Olympic Games,Male,Piotr Władysław•Fijas,Piotr•Fijas,"27 June 1958 in Bielsko-Biała, Śląskie (POL)",NaN,Poland,85710,189 cm / 80 kg,"BBTS Włókniarz Bielsko-Biała, Bielsko-Biała (POL)",NaN,NaN,NaN,NaN,NaN,NaN,Piotr Władysław Fijas
38847,Competed in Olympic Games,Male,Kjetil•Undset,Kjetil•Undset,"24 August 1970 in Stavanger, Rogaland (NOR)",NaN,Norway,39150,201 cm / 95 kg,"Stavanger Roklub, Stavanger (NOR)",NaN,NaN,NaN,NaN,NaN,NaN,Kjetil Undset
68795,Competed in Olympic Games,Male,Roger George•Mills,Roger•Mills,"11 February 1948 in Romford, England (GBR)",NaN,Great Britain,69312,182 cm / 74 kg,"Ilford Athletic Club, Ilford (GBR)",NaN,NaN,NaN,NaN,NaN,NaN,Roger George Mills

In [11]:
# split measurements into height_cm and weight_kg
df[['height_cm', 'weight_kg']] = df["Measurements"].str.split('/', expand=True)

In [ ]:
# find total rows in which there is kg value in height_cm
# len(df[df["height_cm"].astype('str').str.contains("kg")])
# 1182

# 180 cm / 80 kg
# 76 kg

df['height_cm'] = pd.to_numeric(df['height_cm'].str.strip(" cm"), errors="coerce")

df['weight_kg'] = pd.to_numeric(df['weight_kg'].str.strip(' kg'), errors="coerce")

In [22]:
df[['name', 'Measurements','height_cm','weight_kg']].sample(4)

                                  name    Measurements  height_cm  weight_kg
6936    William Edward "Bill" Robinson  180 cm / 71 kg      180.0       71.0
31059    John Frederick Bissinger, Jr.          180 cm      180.0        NaN
117690                  Guntis Galviņš  185 cm / 87 kg      185.0       87.0
143611                  Caroline Marks             NaN        NaN        NaN

In [ ]:
# df[["height_cm", "weight_kg"]].sample(8)
# df[df["height_cm"].notna() & df["weight_kg"].isna()][["name","height_cm", "weight_kg"]].sample(10)

# df[df["weight_kg"].isna()][["name","height_cm", "weight_kg"]]
# df[df["Measurements"].str.split('/').str.len() == 1 & df["Measurements"].str.split('/').str.contains('kg')]

# df[df["Measurements"].str.contains("kg") & ~df["Measurements"].str.contains('cm')]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Akosua Offel,120 kg,NaN
289,Competed in Olympic Games,Male,Ángel•Bello,Ángel•Bello,"9 January 1951 in Vigo, Pontevedra (ESP)",13 June 2013,Argentina,290,65 kg,"Tiro Federal de Lomas de Zamora, Lomas de Zamo...",NaN,NaN,NaN,NaN,NaN,NaN,Ángel Bello,65 kg,NaN
290,Competed in Olympic Games,Male,Claudio A.•Pafundi,Claudio•Pafundi,31 January 1962,NaN,Argentina,291,76 kg,"Tiro Federal General José de San Martín, San M...",NaN,NaN,NaN,NaN,NaN,NaN,Claudio A. Pafundi,76 kg,NaN
1128,Competed in Olympic Games,Male,Jeffrey O.•Alleyne,Jeffrey•Alleyne,"25 June 1938 in Bridgetown, Saint Michael (BAR)",NaN,Canada,1135,71 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jeffrey O. Alleyne,71 kg,NaN
1132,Competed in Olympic Games,Male,"Edward ""Ed""•Beattie",Ed•Beattie,"4 February 1934 in Kilsyth, Scotland (GBR)",NaN,Canada,1139,60 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Edward ""Ed"" Beattie",60 kg,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143193,Competed in Olympic Games,Male,Rejepbaý•Rejepow,Rejepbaý•Rejepow,23 February 1992,NaN,Turkmenistan,146829,81 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rejepbaý Rejepow,81 kg,NaN
143225,Competed in Olympic Games,Male,Chen•Po-Jen,Chen•Po-Jen,11 May 1998,NaN,Chinese Taipei,146865,96 kg,NaN,NaN,NaN,NaN,NaN,陳•柏任,Oriental,Chen Po-Jen,96 kg,NaN
143542,Competed in Olympic Games,Female,Nefeli•Papadakis,Nefeli•Papadakis,"2 October 1998 in Chicago, Illinois (USA)",NaN,United States,147195,78 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nefeli Papadakis,78 kg,NaN
143852,Competed in Olympic Games,Male,Kyle Douglas•Dake,Kyle•Dake,"25 February 1991 in Ithaca, New York (USA)",NaN,United States,147508,79 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kyle Douglas Dake,79 kg,NaN
144122,Competed in Olympic Games,Female,Scarleth•Ucelo Marroquín,Scarleth•Ucelo,7 April 2000,NaN,Guatemala,147795,114 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scarleth Ucelo Marroquín,114 kg,NaN

In [ ]:
df.iloc[143193,:]

Roles            Competed in Olympic Games
Sex                                   Male
Full name                 Rejepbaý•Rejepow
Used name                 Rejepbaý•Rejepow
Born                      23 February 1992
Died                                   NaN
NOC                           Turkmenistan
athlete_id                          146829
Measurements                         81 kg
Affiliations                           NaN
Nick/petnames                          NaN
Title(s)                               NaN
Other names                            NaN
Nationality                            NaN
Original name                          NaN
Name order                             NaN
name                      Rejepbaý Rejepow
height_cm                            81 kg
weight_kg                              NaN
Name: 143193, dtype: object

In [ ]:
# born and dates clearing
df.sample(5)
date_pattern = r"(\d{1,2}\s\w+\s\d{4}|\d{4})"
df["born_date"] = df["Born"].str.extract(date_pattern)
df["born_date"] = pd.to_datetime(df["born_date"], format="mixed", errors="coerce")

In [65]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,born_date_1
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",(FRA),1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"François Joseph Marie Antoine ""Jean-François"" ...",NaN,NaN,1886-12-12,1886-12-12
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,(FRA),2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Benjamin Boetsch,183.0,76.0,1969-04-01,1969-04-01
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",(FRA),3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Laurent Robert Borotra,183.0,76.0,1898-08-13,1898-08-13
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",(FRA),4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Marie Stanislas Jean Brugnon,168.0,64.0,1895-05-11,1895-05-11
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",(GBR),5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Henry Albert Canet,NaN,NaN,1878-04-17,1878-04-17

In [36]:
# Extracting NOC from Born column
# df["NOC"] = df["Born"].str.extract(r'(\(\w{3}\))\s*$')
print(df[["name", "NOC"]].head())

                                                name    NOC
0  François Joseph Marie Antoine "Jean-François" ...  (FRA)
1                            Arnaud Benjamin Boetsch  (FRA)
2                        Jean Laurent Robert Borotra  (FRA)
3               Jacques Marie Stanislas Jean Brugnon  (FRA)
4                                 Henry Albert Canet  (GBR)

In [66]:
# add died date column
df["died_date"] = df["Died"].str.extract(date_pattern)
# convert to date time object
df["died_date"] = pd.to_datetime(df["died_date"], errors="coerce")

In [72]:
# df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  str
 1   Sex            145500 non-null  str
 2   Full name      145500 non-null  str
 3   Used name      145500 non-null  str
 4   Born           143772 non-null  str
 5   Died           34042 non-null   str
 6   NOC            120926 non-null  str
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  str
 9   Affiliations   95832 non-null   str
 10  Nick/petnames  9145 non-null    str
 11  Title(s)       399 non-null     str
 12  Other names    7167 non-null    str
 13  Nationality    8259 non-null    str
 14  Original name  30739 non-null   str
 15  Name order     7844 non-null    str
 16  name           145500 non-null  str
 17  height_cm      106651 non-null  float64
 18  weight_kg      102070 non-null  float64
 19  born_date      143698 non-null  datetime64[us]
 20  died_date      31928 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(2), int64(1), str(16)
memory usage: 48.8 MB

In [78]:
# get city region and ountry from born column
location_pattern = r'in\s([\w\s-]+),\s([\s\w-]+)\s(\(\w{3}\))'
df[["born_city","born_region", "born_country"]] = df["Born"].str.extract(location_pattern, expand=True)

In [79]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,name,height_cm,weight_kg,born_date,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•Blanchy",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-Atlantiques (FRA)",(FRA),1,NaN,NaN,...,NaN,NaN,"François Joseph Marie Antoine ""Jean-François"" Blanchy",NaN,NaN,1886-12-12,1960-10-02,Bordeaux,Gironde,(FRA)
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,(FRA),2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,Arnaud Benjamin Boetsch,183.0,76.0,1969-04-01,NaT,Meulan,Yvelines,(FRA)
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiques (FRA)","17 July 1994 in Arbonne, Pyrénées-Atlantiques (FRA)",(FRA),3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,Jean Laurent Robert Borotra,183.0,76.0,1898-08-13,1994-07-17,Biarritz,Pyrénées-Atlantiques,(FRA)
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",(FRA),4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,Jacques Marie Stanislas Jean Brugnon,168.0,64.0,1895-05-11,1978-03-20,Paris VIIIe,Paris,(FRA)
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",(GBR),5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,Henry Albert Canet,NaN,NaN,1878-04-17,1930-07-25,Wandsworth,England,(GBR)

In [98]:
df.columns
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,name,height_cm,weight_kg,born_date,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•Blanchy",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-Atlantiques (FRA)",(FRA),1,NaN,NaN,...,NaN,NaN,"François Joseph Marie Antoine ""Jean-François"" Blanchy",NaN,NaN,1886-12-12,1960-10-02,Bordeaux,Gironde,(FRA)
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,(FRA),2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,Arnaud Benjamin Boetsch,183.0,76.0,1969-04-01,NaT,Meulan,Yvelines,(FRA)
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiques (FRA)","17 July 1994 in Arbonne, Pyrénées-Atlantiques (FRA)",(FRA),3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,Jean Laurent Robert Borotra,183.0,76.0,1898-08-13,1994-07-17,Biarritz,Pyrénées-Atlantiques,(FRA)
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",(FRA),4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,Jacques Marie Stanislas Jean Brugnon,168.0,64.0,1895-05-11,1978-03-20,Paris VIIIe,Paris,(FRA)
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",(GBR),5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,Henry Albert Canet,NaN,NaN,1878-04-17,1930-07-25,Wandsworth,England,(GBR)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,(RUS),149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",...,NaN,NaN,Polina Luchnikova,167.0,61.0,2002-01-30,NaT,Serov,Sverdlovsk,(RUS)
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (RUS)",NaN,(RUS),149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",...,Валерия Сергеевна•Меркушева,NaN,Valeriya Sergeyevna Merkusheva,168.0,65.0,1999-09-20,NaT,NaN,NaN,NaN
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,(RUS),149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",...,Юлия•Смирнова,NaN,Yuliya Smirnova,163.0,55.0,1998-05-08,NaT,Kotlas,Arkhangelsk,(RUS)
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",(FRA),149225,166 cm,"Beauvoisine FC, Rouen (FRA)",...,NaN,NaN,André Foussard,166.0,NaN,1899-05-19,1986-03-18,Niort,Deux-Sèvres,(FRA)
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales (AUS)","20 October 2003 in Sydney, New South Wales (AUS)",(AUS),149814,NaN,NaN,...,NaN,NaN,"William Berge ""Bill"" Phillips",NaN,NaN,1913-07-15,2003-10-20,Dulwich Hill,New South Wales,(AUS)

In [107]:
columns_to_keep = ["athlete_id", "name", "born_date", "died_date", "born_city", "born_country", "born_region", "height_cm","weight_kg", "NOC"]

In [110]:
df_clean = df[columns_to_keep]
df_clean.head()

,athlete_id,name,born_date,died_date,born_city,born_country,born_region,height_cm,weight_kg,NOC
0,1,"François Joseph Marie Antoine ""Jean-François"" Blanchy",1886-12-12,1960-10-02,Bordeaux,(FRA),Gironde,NaN,NaN,(FRA)
1,2,Arnaud Benjamin Boetsch,1969-04-01,NaT,Meulan,(FRA),Yvelines,183.0,76.0,(FRA)
2,3,Jean Laurent Robert Borotra,1898-08-13,1994-07-17,Biarritz,(FRA),Pyrénées-Atlantiques,183.0,76.0,(FRA)
3,4,Jacques Marie Stanislas Jean Brugnon,1895-05-11,1978-03-20,Paris VIIIe,(FRA),Paris,168.0,64.0,(FRA)
4,5,Henry Albert Canet,1878-04-17,1930-07-25,Wandsworth,(GBR),England,NaN,NaN,(GBR)

In [112]:
# save the file
df_clean.to_csv("cleaned-data/bios-cleaned.csv")