In [1]:
import pandas as pd

In [7]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["Q","B","C"], index=["x","b","w"])


print(df)
print(df.info())
print(df.describe())

   Q  B  C
x  1  2  3
b  4  5  6
w  7  8  9
<class 'pandas.DataFrame'>
Index: 3 entries, x to w
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes
None
         Q    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [9]:
coffee = pd.read_csv("warmup-data/coffee.csv")
print(coffee) # list all
print(coffee.head()) # list top 5

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [18]:
coffee_2 = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")

print(coffee_2.head())

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
# parquet_data = pd.read_parquet("data/results.parquet")
# print(parquet_data.head())

ArrowKeyError: A type extension with name pandas.period already defined

In [23]:
bios_csv = pd.read_csv("data/bios.csv")
print(bios_csv.head())

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25

In [3]:
olympics_data = pd.read_excel("data/olympics-data.xlsx")

print(olympics_data.head())

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25

In [4]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [10]:
olympics_data.loc[[0,2,3]]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20

In [16]:
olympics_data.loc[2:3]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20

In [ ]:
coffee_2.loc[2:4, ["Day","Coffee Type"]]
# df.loc[#rows,#columns]

         Day Coffee Type
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso

In [26]:
coffee_2.loc[3:8,["Day"]]

         Day
3    Tuesday
4  Wednesday
5  Wednesday
6   Thursday
7   Thursday
8     Friday

In [73]:
# add indexes for other columns
# we can assign a different column as index
# coffee_2.index = coffee_2["Coffee Type"]
# coffee_2

coffee_2.reset_index(drop=True, inplace=True)
coffee_2.sort_values(by="Units Sold")
print(coffee_2)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [29]:
# .iloc
# df.iloc[rows, columns]
#  in iloc we only need indexes for both rows and columns
# eg.
coffee_2.iloc[3:9,[0]]

         Day
3    Tuesday
4  Wednesday
5  Wednesday
6   Thursday
7   Thursday
8     Friday

In [55]:
coffee_2.loc["15:40"]

KeyError: '15:40'

In [74]:
coffee3 = pd.read_csv("warmup-data/coffee.csv")

In [76]:
print(coffee3)
coffee3.sort_values(by="Units Sold")

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [79]:
coffee3.index = coffee3["Units Sold"]
print(coffee3)
coffee3.loc[15:20]

                  Day Coffee Type  Units Sold
Units Sold
25             Monday    Espresso          25
15             Monday       Latte          15
30            Tuesday    Espresso          30
20            Tuesday       Latte          20
35          Wednesday    Espresso          35
25          Wednesday       Latte          25
40           Thursday    Espresso          40
30           Thursday       Latte          30
45             Friday    Espresso          45
35             Friday       Latte          35
45           Saturday    Espresso          45
35           Saturday       Latte          35
45             Sunday    Espresso          45
35             Sunday       Latte          35

                Day Coffee Type  Units Sold
Units Sold
15           Monday       Latte          15
30          Tuesday    Espresso          30
20          Tuesday       Latte          20

In [80]:
coffee3.index = coffee3["Day"]

In [82]:
print(coffee3)

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [84]:
coffee3.loc["Monday":"Wednesday"]

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

In [3]:
coffee_4 = pd.read_csv("warmup-data/coffee.csv")
print(coffee_4)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [20]:
# coffee_4.loc[4, "Coffee Type"] = "Milk Latte _1"

coffee_4.rename(columns={(4, "Coffee Type"): "Type_1"}, inplace=True)

print(coffee_4)

          Day    Coffee Type  Units Sold      Type_1
0      Monday       Espresso          25  Milk Latte
1      Monday          Latte          15  Milk Latte
2     Tuesday       Espresso          30  Milk Latte
3     Tuesday          Latte          20  Milk Latte
4   Wednesday  Milk Latte _1          35  Milk Latte
5   Wednesday          Latte          25  Milk Latte
6    Thursday       Espresso          40  Milk Latte
7    Thursday          Latte          30  Milk Latte
8      Friday       Espresso          45  Milk Latte
9      Friday          Latte          35  Milk Latte
10   Saturday       Espresso          45  Milk Latte
11   Saturday          Latte          35  Milk Latte
12     Sunday       Espresso          45  Milk Latte
13     Sunday          Latte          35  Milk Latte

In [21]:
coffee_4.columns = ["Day_1","Cof Type", "Units", "T1"]

In [23]:
print(coffee_4.head())

       Day_1       Cof Type  Units          T1
0     Monday       Espresso     25  Milk Latte
1     Monday          Latte     15  Milk Latte
2    Tuesday       Espresso     30  Milk Latte
3    Tuesday          Latte     20  Milk Latte
4  Wednesday  Milk Latte _1     35  Milk Latte

In [ ]:
# .at[rows, columns]
# .iat[rows,columns]

In [2]:
import pandas as pd
coffee_5  = pd.read_csv("warmup-data/coffee.csv")

In [22]:
print(coffee_5)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [23]:
coffee_5.at[1,"Coffee Type"] = "My Latte"
print(coffee_5)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday    My Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [26]:
coffee_5.iat[1,2] = 50
print(coffee_5)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday    My Latte          50
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [8]:
# getting a specific column
days = coffee_5.Day
units = coffee_5["Units Sold"]

print(days)
print(units)

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str
0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [ ]:
# sorting the values
coffee_5.sort_values("Day",ascending=False)

# specifying two columns for sorting
coffee_5.sort_values(["Day", "Coffee Type"], ascending=[1,1])
# in this above we pass two column names in array to sort, after that we pass one array for ascending which indidates the sorting for each column 0 => sort ascending = True, 1 => sort ascending = False

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
9      Friday       Latte          35
0      Monday    Espresso          25
1      Monday       Latte          15
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35
6    Thursday    Espresso          40
7    Thursday       Latte          30
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25

In [21]:
olympics = pd.read_csv("data/bios.csv")
print(olympics)

        athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux
1                2         Arnaud Boetsch  1969-04-01           Meulan
2                3           Jean Borotra  1898-08-13         Biarritz
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe
4                5           Albert Canet  1878-04-17       Wandsworth
...            ...                    ...         ...              ...
145495      149222      Polina Luchnikova  2002-01-30            Serov
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas
145498      149225         André Foussard  1899-05-19            Niort
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN
1                   Yvelines          FRA     France      183.0       76.0
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0
3                      Paris          FRA     France      168.0       64.0
4                    England          GBR     France        NaN        NaN
...                      ...          ...        ...        ...        ...
145495            Sverdlovsk          RUS        ROC      167.0       61.0
145496                Moskva          RUS        ROC      168.0       65.0
145497           Arkhangelsk          RUS        ROC      163.0       55.0
145498           Deux-Sèvres          FRA     France      166.0        NaN
145499       New South Wales          AUS  Australia        NaN        NaN

         died_date
0       1960-10-02
1              NaN
2       1994-07-17
3       1978-03-20
4       1930-07-25
...            ...
145495         NaN
145496         NaN
145497         NaN
145498  1986-03-18
145499  2003-10-20

[145500 rows x 10 columns]

In [22]:
olympics.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [84]:
# get atheletes who has height greater than 200 cm
# oly_h_d = olympics.loc[(olympics.height_cm > 200), ["name","born_date","height_cm"]].sort_values(by="height_cm")
# print(oly_h_d)

print(len(olympics))

olympics_bio_filterd_by_height = olympics.loc[(olympics["height_cm"] >=190), ["name", "born_date", "height_cm"]]
sorted_by_height = olympics_bio_filterd_by_height.sort_values(by="height_cm", ascending=False)
print(olympics_bio_filterd_by_height)
print(len(sorted_by_height))

145500
                    name   born_date  height_cm
47            Sara Gomer  1964-05-13      190.0
79            Neil Broad  1966-11-20      191.0
81         Andrew Castle  1963-11-15      190.0
105        Harold Mahony  1867-02-13      191.0
114        Greg Rusedski  1973-09-06      190.0
...                  ...         ...        ...
145257     Pavol Regenda  1999-12-07      192.0
145259  Juraj Slafkovský  2004-03-30      192.0
145261       Matej Tomek  1997-05-24      191.0
145263     Marián Skupek  2001-07-12      196.0
145459   Roberts Mamčics  1995-04-06      196.0

[11090 rows x 3 columns]
11090

In [ ]:
# we can add multiple conditions in loc for filtering data
# e.g. get player names whose height is above 200 cm and born country = USA

# print(olympics)

filtered_data = olympics.loc[(olympics["height_cm"] >= 190) & (olympics["born_country"] == "USA"), ["name", "born_country", "height_cm"]]
print(filtered_data)

                     name born_country  height_cm
2225        Butch Johnson          USA      191.0
2712    Lindsay Davenport          USA      191.0
2736           Jim Butler          USA      193.0
2762          Tim Mayotte          USA      190.0
2775        Robert Seguso          USA      191.0
...                   ...          ...        ...
143836          Alex Wolf          USA      200.0
143838       Drew Holland          USA      195.0
143984     Keldon Johnson          USA      196.0
144005          Ike Nwamu          USA      196.0
144056        Alen Hadzic          USA      190.0

[1163 rows x 3 columns]

In [90]:
print(olympics)

        athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux
1                2         Arnaud Boetsch  1969-04-01           Meulan
2                3           Jean Borotra  1898-08-13         Biarritz
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe
4                5           Albert Canet  1878-04-17       Wandsworth
...            ...                    ...         ...              ...
145495      149222      Polina Luchnikova  2002-01-30            Serov
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas
145498      149225         André Foussard  1899-05-19            Niort
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN
1                   Yvelines          FRA     France      183.0       76.0
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0
3                      Paris          FRA     France      168.0       64.0
4                    England          GBR     France        NaN        NaN
...                      ...          ...        ...        ...        ...
145495            Sverdlovsk          RUS        ROC      167.0       61.0
145496                Moskva          RUS        ROC      168.0       65.0
145497           Arkhangelsk          RUS        ROC      163.0       55.0
145498           Deux-Sèvres          FRA     France      166.0        NaN
145499       New South Wales          AUS  Australia        NaN        NaN

         died_date
0       1960-10-02
1              NaN
2       1994-07-17
3       1978-03-20
4       1930-07-25
...            ...
145495         NaN
145496         NaN
145497         NaN
145498  1986-03-18
145499  2003-10-20

[145500 rows x 10 columns]

In [ ]:
# .query() function

olympics.query('height_cm > 190 and born_country in ["USA","GBE"]')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2225,2235,Butch Johnson,1955-08-30,Worcester,Massachusetts,USA,United States,191.0,98.0,NaN
2712,2724,Lindsay Davenport,1976-06-08,Palos Verdes,California,USA,United States,191.0,79.0,NaN
2736,2748,Jim Butler,1971-02-15,Iowa City,Iowa,USA,United States,193.0,77.0,NaN
2775,2787,Robert Seguso,1963-05-01,Minneapolis,Minnesota,USA,United States,191.0,82.0,NaN
2785,2797,Watty Washburn,1894-06-13,New York,New York,USA,United States,194.0,NaN,1973-12-02
...,...,...,...,...,...,...,...,...,...,...
143813,147469,Drew Kibler,2000-03-09,Indianapolis,Indiana,USA,United States,196.0,NaN,NaN
143836,147492,Alex Wolf,1997-04-19,Anaheim,California,USA,United States,200.0,NaN,NaN
143838,147494,Drew Holland,1995-04-11,Berkeley,California,USA,United States,195.0,NaN,NaN
143984,147642,Keldon Johnson,1999-10-11,Chesterfield,Virginia,USA,United States,196.0,NaN,NaN
144005,147669,Ike Nwamu,1993-06-03,Greensboro,North Carolina,USA,Nigeria,196.0,92.0,NaN

In [ ]:
# we can also pass dynamic list
countries_to_fetch = ["USA", "FR"]
olympics.query('height_cm > 190 and born_country in @countries_to_fetch')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2225,2235,Butch Johnson,1955-08-30,Worcester,Massachusetts,USA,United States,191.0,98.0,NaN
2712,2724,Lindsay Davenport,1976-06-08,Palos Verdes,California,USA,United States,191.0,79.0,NaN
2736,2748,Jim Butler,1971-02-15,Iowa City,Iowa,USA,United States,193.0,77.0,NaN
2775,2787,Robert Seguso,1963-05-01,Minneapolis,Minnesota,USA,United States,191.0,82.0,NaN
2785,2797,Watty Washburn,1894-06-13,New York,New York,USA,United States,194.0,NaN,1973-12-02
...,...,...,...,...,...,...,...,...,...,...
143813,147469,Drew Kibler,2000-03-09,Indianapolis,Indiana,USA,United States,196.0,NaN,NaN
143836,147492,Alex Wolf,1997-04-19,Anaheim,California,USA,United States,200.0,NaN,NaN
143838,147494,Drew Holland,1995-04-11,Berkeley,California,USA,United States,195.0,NaN,NaN
143984,147642,Keldon Johnson,1999-10-11,Chesterfield,Virginia,USA,United States,196.0,NaN,NaN
144005,147669,Ike Nwamu,1993-06-03,Greensboro,North Carolina,USA,Nigeria,196.0,92.0,NaN

In [103]:
# add remove columns

new_coffee = pd.read_csv("warmup-data/coffee.csv")
print(new_coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [104]:
# add column nme price
new_coffee['price'] = 4.99
print(new_coffee)

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [ ]:
# add new price column with different price for different coffee type
import numpy as np
new_coffee["new_price"] = np.where(new_coffee["Coffee Type"] == "Espresso", 3.99, 5.99)
print(new_coffee)

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [ ]:
# drop price column
# inplace=True modify actual dataframe, default is inplace=False
# new_coffee.drop(columns=['price'], inplace=True)
print(new_coffee)

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [119]:
# copy a dataframe into new dataframe
new_new_coffee = new_coffee.copy()
print(new_new_coffee)
# new_coffee.drop(columns=["new_price"])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [126]:
# add revenue column in new_coffee dataframe
new_coffee["revenue"] = new_coffee["Units Sold"] * new_coffee["new_price"]
print(new_coffee)

# get days where revenue is greater than 150 USD
new_coffee.iloc[np.where(new_coffee["revenue"] > 150)]

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

         Day Coffee Type  Units Sold  new_price  revenue
6   Thursday    Espresso          40       3.99   159.60
7   Thursday       Latte          30       5.99   179.70
8     Friday    Espresso          45       3.99   179.55
9     Friday       Latte          35       5.99   209.65
10  Saturday    Espresso          45       3.99   179.55
11  Saturday       Latte          35       5.99   209.65
12    Sunday    Espresso          45       3.99   179.55
13    Sunday       Latte          35       5.99   209.65

In [130]:
# .rename() method
new_coffee.rename(columns={"new_price": "price"}, inplace=True)
print(new_coffee)

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [132]:
olympics_bios = pd.read_csv("data/bios.csv")
new_olympics_bios = olympics_bios.copy()
print(new_olympics_bios.head())

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25

In [ ]:
# TODO: add new column called first name and birth year which in new_olympics_bios dataframe

print(new_olympics_bios[["name","born_date"]])

new_olympics_bios["first_name"] = new_olympics_bios["name"].str.split(" ").str[0]
new_olympics_bios["birth_year"] = new_olympics_bios["born_date"].str.split('-').str[0].astype('Int64')


print(new_olympics_bios[["name","first_name","born_date","birth_year"]])

                         name   born_date
0       Jean-François Blanchy  1886-12-12
1              Arnaud Boetsch  1969-04-01
2                Jean Borotra  1898-08-13
3             Jacques Brugnon  1895-05-11
4                Albert Canet  1878-04-17
...                       ...         ...
145495      Polina Luchnikova  2002-01-30
145496    Valeriya Merkusheva  1999-09-20
145497        Yuliya Smirnova  1998-05-08
145498         André Foussard  1899-05-19
145499          Bill Phillips  1913-07-15

[145500 rows x 2 columns]
                         name     first_name   born_date  birth_year
0       Jean-François Blanchy  Jean-François  1886-12-12        1886
1              Arnaud Boetsch         Arnaud  1969-04-01        1969
2                Jean Borotra           Jean  1898-08-13        1898
3             Jacques Brugnon        Jacques  1895-05-11        1895
4                Albert Canet         Albert  1878-04-17        1878
...                       ...            ...         ...         ...
145495      Polina Luchnikova         Polina  2002-01-30        2002
145496    Valeriya Merkusheva       Valeriya  1999-09-20        1999
145497        Yuliya Smirnova         Yuliya  1998-05-08        1998
145498         André Foussard          André  1899-05-19        1899
145499          Bill Phillips           Bill  1913-07-15        1913

[145500 rows x 4 columns]

In [161]:
# get players whose birth year is greater than 1998
players_filtered = new_olympics_bios.loc[(new_olympics_bios["birth_year"] > 1998), ["name", "birth_year", "born_date"]]
print(players_filtered)

new_olympics_bios.info()

                       name  birth_year   born_date
118458          Adzo Kpossi        1999  1999-01-25
126494      Farah Boufadene        1999  1999-03-11
126497        Fatima Hirech        2000  2000-08-22
126509     Samantha Roberts        2000  2000-04-21
126545       Fernanda Russo        1999  1999-10-02
...                     ...         ...         ...
145484           Gao Hongbo        2000  2000-10-20
145488         Shakeel John        2001  2001-07-30
145489           Ye Jielong        2000  2000-03-02
145495    Polina Luchnikova        2002  2002-01-30
145496  Valeriya Merkusheva        1999  1999-09-20

[4251 rows x 3 columns]
<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  first_name    145500 non-null  object
 11  birth_year    143693 non-null  Int64
dtypes: Int64(1), float64(2), int64(1), object(1), str(7)
memory usage: 20.9+ MB

In [177]:
# datetime conversion
# pd.to_datetime

new_olympics_bios["born_date_1"] = pd.to_datetime(new_olympics_bios["born_date"])

new_olympics_bios["year_1"] = pd.to_datetime(new_olympics_bios["born_date"], format="%Y-%m-%d").dt.year.astype("Int64")



new_olympics_bios.info()

print(new_olympics_bios[["name","first_name","born_date","birth_year", "year_1"]])

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  first_name    145500 non-null  object
 11  birth_year    143693 non-null  Int64
 12  year_1        143693 non-null  Int64
 13  born_date_1   143693 non-null  datetime64[us]
dtypes: Int64(2), datetime64[us](1), float64(2), int64(1), object(1), str(7)
memory usage: 23.2+ MB
                         name     first_name   born_date  birth_year  year_1
0       Jean-François Blanchy  Jean-François  1886-12-12        1886    1886
1              Arnaud Boetsch         Arnaud  1969-04-01        1969    1969
2                Jean Borotra           Jean  1898-08-13        1898    1898
3             Jacques Brugnon        Jacques  1895-05-11        1895    1895
4                Albert Canet         Albert  1878-04-17        1878    1878
...                       ...            ...         ...         ...     ...
145495      Polina Luchnikova         Polina  2002-01-30        2002    2002
145496    Valeriya Merkusheva       Valeriya  1999-09-20        1999    1999
145497        Yuliya Smirnova         Yuliya  1998-05-08        1998    1998
145498         André Foussard          André  1899-05-19        1899    1899
145499          Bill Phillips           Bill  1913-07-15        1913    1913

[145500 rows x 5 columns]

In [1]:
import pandas as pd
import numpy as np
olybios = pd.read_csv("data/bios.csv")
nocs = pd.read_csv("data/noc_regions.csv")
print(olybios.head())
print(nocs.head())

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25
   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [27]:
# merging two data frames / joining two data frames
# this is similar to mysql joins
# pd.merge(df1, df2, left_on="", right_on="", how="left | inner | right")

merged_new = pd.merge(olybios, nocs, left_on="born_country", right_on="NOC", how="left")
merged_new.rename(columns={"region": "full_country_name"}, inplace=True)
merged_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,full_country_name,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [30]:
print(merged_new[["name","full_country_name","born_country"]])

                         name full_country_name born_country
0       Jean-François Blanchy            France          FRA
1              Arnaud Boetsch            France          FRA
2                Jean Borotra            France          FRA
3             Jacques Brugnon            France          FRA
4                Albert Canet                UK          GBR
...                       ...               ...          ...
145495      Polina Luchnikova            Russia          RUS
145496    Valeriya Merkusheva            Russia          RUS
145497        Yuliya Smirnova            Russia          RUS
145498         André Foussard            France          FRA
145499          Bill Phillips         Australia          AUS

[145500 rows x 3 columns]

In [40]:
# concat two df

fra_df = merged_new[merged_new["born_country"] == "FRA"]
gbr_df = merged_new[merged_new["born_country"] == "GBR"]


# print(fra_df.head())
# print(gbr_df.head())

# concat fra_df and gbr_df
new_merged = pd.concat([fra_df,gbr_df])
print(new_merged.tail()[["name","born_country"]])

                      name born_country
144811  Benjamin Alexander          GBR
144815       Ashley Watson          GBR
145005     Peder Kongshaug          GBR
145319          Axel Brown          GBR
145388      Jean-Luc Baker          GBR

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)  
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

In [19]:
df_bios = pd.read_csv("data/bios.csv")
df_olympics = pd.read_excel("data/olympics-data.xlsx")
df_regions = pd.read_csv("data/noc_regions.csv")

In [22]:
print(df_bios.head())
print('-x-')
# print(df_olympics.head())
print('-x-')
# print(df_regions.head())

   athlete_id                   name   born_date    born_city           born_region born_country     NOC  height_cm  weight_kg   died_date
0           1  Jean-François Blanchy  1886-12-12     Bordeaux               Gironde          FRA  France        NaN        NaN  1960-10-02
1           2         Arnaud Boetsch  1969-04-01       Meulan              Yvelines          FRA  France      183.0       76.0         NaN
2           3           Jean Borotra  1898-08-13     Biarritz  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe                 Paris          FRA  France      168.0       64.0  1978-03-20
4           5           Albert Canet  1878-04-17   Wandsworth               England          GBR  France        NaN        NaN  1930-07-25
-x-
-x-

In [21]:
results = pd.read_parquet('data/results.parquet')
print(results)

          year    type              discipline                          event                     as  athlete_id  noc             team  place   tied medal
0       1912.0  Summer                  Tennis         Singles, Men (Olympic)  Jean-François Blanchy           1  FRA              NaN   17.0   True   NaN
1       1912.0  Summer                  Tennis         Doubles, Men (Olympic)  Jean-François Blanchy           1  FRA   Jean Montariol    NaN  False   NaN
2       1920.0  Summer                  Tennis         Singles, Men (Olympic)  Jean-François Blanchy           1  FRA              NaN   32.0   True   NaN
3       1920.0  Summer                  Tennis       Doubles, Mixed (Olympic)  Jean-François Blanchy           1  FRA  Jeanne Vaussard    8.0   True   NaN
4       1920.0  Summer                  Tennis         Doubles, Men (Olympic)  Jean-François Blanchy           1  FRA  Jacques Brugnon    4.0  False   NaN
...        ...     ...                     ...                            ...                    ...         ...  ...              ...    ...    ...   ...
308403  2022.0  Winter                    Luge         Singles, Men (Olympic)          Marián Skupek      148983  SVK              NaN   26.0  False   NaN
308404  2022.0  Winter  Alpine Skiing (Skiing)        Slalom, Women (Olympic)          Elsa Fermbäck      148984  SWE              NaN   28.0  False   NaN
308405  2022.0  Winter  Alpine Skiing (Skiing)          Team, Mixed (Olympic)          Hilma Lövblom      148985  SWE           Sweden   13.0  False   NaN
308406  2022.0  Winter  Alpine Skiing (Skiing)  Giant Slalom, Women (Olympic)          Hilma Lövblom      148985  SWE              NaN    NaN  False   NaN
308407  2022.0  Winter                     NaN        Slalom, Women (Olympic)   Charlotta Säfvenberg      148986  NaN              NaN   24.0  False   NaN

[308408 rows x 11 columns]

In [27]:
# merge results with bios
df_bios_result_merged = pd.merge(df_bios, results, left_on="athlete_id", right_on="athlete_id", how="left")

print(df_bios_result_merged[["athlete_id","name","event", "discipline"]].head())

   athlete_id                   name                     event discipline
0           1  Jean-François Blanchy    Singles, Men (Olympic)     Tennis
1           1  Jean-François Blanchy    Doubles, Men (Olympic)     Tennis
2           1  Jean-François Blanchy    Singles, Men (Olympic)     Tennis
3           1  Jean-François Blanchy  Doubles, Mixed (Olympic)     Tennis
4           1  Jean-François Blanchy    Doubles, Men (Olympic)     Tennis

In [29]:
df_coffee = pd.read_csv("warmup-data/coffee.csv")

In [ ]:
# interpolation
# df_coffee.loc[[1,2],"Units Sold"] = np.nan

In [ ]:
df_coffee["Units Sold"] = df_coffee["Units Sold"].interpolate()  
# interpolate will fill the missing values with the average of previous and next values

In [ ]:
df_coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso   25.000000
1      Monday       Latte   23.333333
2     Tuesday    Espresso   21.666667
3     Tuesday       Latte   20.000000
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000

In [4]:
# .value_counts method

df_bios = pd.read_csv("data/bios.csv")

In [5]:
df_bios

        athlete_id                   name   born_date        born_city           born_region born_country        NOC  height_cm  weight_kg   died_date
0                1  Jean-François Blanchy  1886-12-12         Bordeaux               Gironde          FRA     France        NaN        NaN  1960-10-02
1                2         Arnaud Boetsch  1969-04-01           Meulan              Yvelines          FRA     France      183.0       76.0         NaN
2                3           Jean Borotra  1898-08-13         Biarritz  Pyrénées-Atlantiques          FRA     France      183.0       76.0  1994-07-17
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe                 Paris          FRA     France      168.0       64.0  1978-03-20
4                5           Albert Canet  1878-04-17       Wandsworth               England          GBR     France        NaN        NaN  1930-07-25
...            ...                    ...         ...              ...                   ...          ...        ...        ...        ...         ...
145495      149222      Polina Luchnikova  2002-01-30            Serov            Sverdlovsk          RUS        ROC      167.0       61.0         NaN
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)                Moskva          RUS        ROC      168.0       65.0         NaN
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas           Arkhangelsk          RUS        ROC      163.0       55.0         NaN
145498      149225         André Foussard  1899-05-19            Niort           Deux-Sèvres          FRA     France      166.0        NaN  1986-03-18
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill       New South Wales          AUS  Australia        NaN        NaN  2003-10-20

[145500 rows x 10 columns]

In [6]:
# count total athtletes by born_country

df_bios.value_counts(df_bios["born_country"])

born_country
USA       9641
GER       6891
GBR       5792
FRA       5143
ITA       4709
          ...
Havel        1
SMT          1
COK          1
Corfu        1
Aarhus       1
Name: count, Length: 236, dtype: int64

In [ ]:
# count get by born_city
df_bios["born_city"].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [9]:
df_bios.value_counts(df_bios["born_country"])

born_country
USA       9641
GER       6891
GBR       5792
FRA       5143
ITA       4709
          ...
Havel        1
SMT          1
COK          1
Corfu        1
Aarhus       1
Name: count, Length: 236, dtype: int64

In [18]:
df_bios[df_bios["born_country"] == 'USA']["born_region"].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [22]:
df_bios[df_bios['born_country'] == 'USA']["born_city"].value_counts()

born_city
New York               416
Chicago                283
Los Angeles            230
Philadelphia           205
Boston                 153
                      ...
North Billerica          1
Delano                   1
Grosse Pointe Woods      1
Mount Shasta             1
McHenry                  1
Name: count, Length: 2255, dtype: int64

In [26]:
df_coffee = pd.read_csv("warmup-data/coffee.csv")
df_coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
# groupby function for aggregation of data
# get total units sold by each coffee type in a given data
df_coffee.groupby("Coffee Type")["Units Sold"].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [31]:
# get average coffee units sold for each coffee type

print(df_coffee.groupby("Coffee Type")["Units Sold"].mean())

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [36]:
# add price column in df_coffee
df_coffee["Price"] = np.where(df_coffee['Coffee Type'] == 'Expresso',3.99, 6.99)
print(df_coffee
      )

# add a column total revenue
df_coffee["Total Revenue"] = df_coffee["Units Sold"] * df_coffee["Price"]

print(df_coffee
      )

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   6.99
1      Monday       Latte          15   6.99
2     Tuesday    Espresso          30   6.99
3     Tuesday       Latte          20   6.99
4   Wednesday    Espresso          35   6.99
5   Wednesday       Latte          25   6.99
6    Thursday    Espresso          40   6.99
7    Thursday       Latte          30   6.99
8      Friday    Espresso          45   6.99
9      Friday       Latte          35   6.99
10   Saturday    Espresso          45   6.99
11   Saturday       Latte          35   6.99
12     Sunday    Espresso          45   6.99
13     Sunday       Latte          35   6.99
          Day Coffee Type  Units Sold  Price  Total Revenue
0      Monday    Espresso          25   6.99         174.75
1      Monday       Latte          15   6.99         104.85
2     Tuesday    Espresso          30   6.99         209.70
3     Tuesday       Latte          20   6.99         139.80
4   Wednesday    Espresso          35   6.99         244.65
5   Wednesday       Latte          25   6.99         174.75
6    Thursday    Espresso          40   6.99         279.60
7    Thursday       Latte          30   6.99         209.70
8      Friday    Espresso          45   6.99         314.55
9      Friday       Latte          35   6.99         244.65
10   Saturday    Espresso          45   6.99         314.55
11   Saturday       Latte          35   6.99         244.65
12     Sunday    Espresso          45   6.99         314.55
13     Sunday       Latte          35   6.99         244.65

In [ ]:
# aggreggate by multiple columns
# .agg function
df_coffee.groupby('Coffee Type').agg({
  "Units Sold": "sum",
  "Total Revenue": "mean"
})

             Units Sold  Total Revenue
Coffee Type
Espresso            265     264.621429
Latte               195     194.721429

In [42]:
# calcluate sum per day
df_coffee.groupby("Day").agg({
  "Units Sold": "sum"
}).sort_values(by="Units Sold")

           Units Sold
Day
Monday             40
Tuesday            50
Wednesday          60
Thursday           70
Sunday             80
Saturday           80
Friday             80