In [1]:
import pandas as pd

In [7]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["Q","B","C"], index=["x","b","w"])


print(df)
print(df.info())
print(df.describe())

   Q  B  C
x  1  2  3
b  4  5  6
w  7  8  9
<class 'pandas.DataFrame'>
Index: 3 entries, x to w
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes
None
         Q    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [9]:
coffee = pd.read_csv("warmup-data/coffee.csv")
print(coffee) # list all
print(coffee.head()) # list top 5

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35
         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [18]:
coffee_2 = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")

print(coffee_2.head())

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
# parquet_data = pd.read_parquet("data/results.parquet")
# print(parquet_data.head())

ArrowKeyError: A type extension with name pandas.period already defined

In [23]:
bios_csv = pd.read_csv("data/bios.csv")
print(bios_csv.head())

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25

In [3]:
olympics_data = pd.read_excel("data/olympics-data.xlsx")

print(olympics_data.head())

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25

In [4]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [10]:
olympics_data.loc[[0,2,3]]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20

In [16]:
olympics_data.loc[2:3]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20

In [ ]:
coffee_2.loc[2:4, ["Day","Coffee Type"]]
# df.loc[#rows,#columns]

         Day Coffee Type
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso

In [26]:
coffee_2.loc[3:8,["Day"]]

         Day
3    Tuesday
4  Wednesday
5  Wednesday
6   Thursday
7   Thursday
8     Friday

In [29]:
# .iloc
# df.iloc[rows, columns]
#  in iloc we only need indexes for both rows and columns
# eg.
coffee_2.iloc[3:9,[0]]

         Day
3    Tuesday
4  Wednesday
5  Wednesday
6   Thursday
7   Thursday
8     Friday